const weatherMap: { [name: string]: string } = {
  晴: require('./../../assets/svg/icon_0.svg'),
  阴: require('./../../assets/svg/icon_1.svg'),
  多云: require('./../../assets/svg/icon_2.svg'),
  多云转晴: require('./../../assets/svg/icon_2.svg'),
  晴转多云: require('./../../assets/svg/icon_2.svg'),
  小雨: require('./../../assets/svg/icon_3.svg'),
  雨: require('./../../assets/svg/icon_4.svg'),
  中雨: require('./../../assets/svg/icon_4.svg'),
  大雨: require('./../../assets/svg/icon_5.svg'),
  雷阵雨: require('./../../assets/svg/icon_6.svg'),
  冰雹: require('./../../assets/svg/icon_7.svg'),
  暴雨: require('./../../assets/svg/icon_8.svg'),
  特大暴雨: require('./../../assets/svg/icon_9.svg'),
  小雪: require('./../../assets/svg/icon_10.svg'),
  雪: require('./../../assets/svg/icon_11.svg'),
  中雪: require('./../../assets/svg/icon_11.svg'),
  雨夹雪: require('./../../assets/svg/icon_12.svg'),
  大雪: require('./../../assets/svg/icon_13.svg'),
  浮尘: require('./../../assets/svg/icon_14.svg'),
  扬沙: require('./../../assets/svg/icon_15.svg'),
  沙尘暴: require('./../../assets/svg/icon_15.svg'),
  大暴雪: require('./../../assets/svg/icon_16.svg'),
  雾: require('./../../assets/svg/icon_17.svg'),
  雾霾: require('./../../assets/svg/icon_18.svg'),
  飓风: require('./../../assets/svg/icon_19.svg'),
  龙卷风: require('./../../assets/svg/icon_20.svg'),
  风: require('./../../assets/svg/icon_21.svg'),
  大风: require('./../../assets/svg/icon_22.svg'),
  unknown: require('./../../assets/svg/icon_23.svg'),
};

export default weatherMap;
